name: Docker Image Build and Publish to GitHub Container Registry
permissions: write-all

on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker buildx create --use
          docker build . --tag ghcr.io/r3dlessx/epf-building-access-pass:latest
          docker push ghcr.io/r3dlessx/epf-building-access-pass:latest